name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  statuses: write
  checks: write
  contents: write
  pull-requests: write

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: composer run-script test

     - name: List test report directory
       run: ls -l tests

    - name: Display test report content
      run: cat tests/phpunit.xml

    - name: Test Reporter
      uses: dorny/test-reporter@v1.9.1
      if: success() || failure()    # Exécuter cette étape même si l'étape précédente échoue
      with:
        name: Report PhpUnit Tests           # Nom du check run qui sera créé
        path: tests/phpunit.xml              # Chemin du fichier de rapport
        reporter: java-junit